auth:
  login-url: "http://localhost:8081/api/auth/login"
  public-key-url: "http://localhost:8081/api/auth/public-key"


spring:
  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: users-api
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: products-api
          uri: http://localhost:8083
          predicates:
            - Path=/products/**