auth:
  login-url: "http://authapi:8081/auth/login"
  public-key-url: "http://authapi:8081/auth/public-key"

eureka:
  client:
    enabled: false

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: http://authapi:8081
          predicates:
            - Path=/auth/**
        - id: users-api
          uri: http://usersapi:8082
          predicates:
            - Path=/admin/**
        - id: products-api
          uri: http://productsapi:8083
          predicates:
            - Path=/products/**