auth:
  login-url: "http://localhost:8081/auth/login"
  public-key-url: "http://localhost:8081/auth/public-key"

eureka:
  client:
    enabled: false

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
#      global cors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
#            allowedCredentials: true
      routes:
        - id: auth-api
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: users-api
          uri: http://localhost:8082
          predicates:
            - Path=/admin/**
        - id: products-api
          uri: http://localhost:8083
          predicates:
            - Path=/products/**